apps/components/urls.py
from django.conf.urls import url

from apps.components.views import create_component, ComponentsList

app_name = 'components'

urlpatterns = [
    url(r'^$', ComponentsList.as_view(), name='components_list'),
    url(r'^new$', create_component, name='new_component'),
]

semisklad/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^components/', include('apps.components.urls')),
    url(r'^storage/', include('apps.storage.urls')),
    url(r'^suppliers/', include('apps.suppliers.urls')),
    url(r'^workers/', include('apps.workers.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.common.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static "images/SOM.png" %}">

    <title>SemiSklad</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="{% static "css/ie10-viewport-bug-workaround.css" %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static "css/navbar-fixed-top.css" %}" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="{% static "js/ie-emulation-modes-warning.js" %}"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <style>
        body {
            background: url({% static "images/sklad_1.jpg" %}) no-repeat center center fixed;
            background-size: cover;
        }
        .message {
            height: 80px;
            width: 100%;
        }
        .error {
            background-color: firebrick;
        }
        .success {
            background-color: limegreen;
        }
        .content{
            background-color: ghostwhite;
            opacity: 0.9;
            border-radius: 10px;
            width: 60%;
            margin-left: 20%;
            margin-bottom: 10px;
            padding: 20px 50px 20px 50px;
            min-height: 70%;
            position: absolute;
        }
        #lcol{
            opacity: 0.95;
            background-color: ghostwhite;
            border-radius: 10px;
            width: 18%;
            margin-left: 1%;
            margin-bottom: 10px;
            padding: 20px 50px 20px 50px;
            min-height: 70%;
            position: absolute;
        }
        #rcol{
            opacity: 0.95;
            background-color: ghostwhite;
            border-radius: 10px;
            width: 18%;
            margin-left: 81%;
            margin-bottom: 10px;
            padding: 20px 50px 20px 50px;
            min-height: 70%;
            position: absolute;
        }

    </style>
</head>

<body>

{% block header %}
    {% include 'header.html' %}
{% endblock header %}

{# Error and success messges #}
{% if messages %}
{#<ul class="messages">#}
{#    {% for message in messages.error %}#}
{#    <li class="alert alert-danger" role="alert">{{ message }}</li>#}
{#    {% endfor %}#}
{#    {% for message in messages.success %}#}
{#    <li class="alert alert-success" role="alert">{{ message }}</li>#}
{#    {% endfor %}#}
{#</ul>#}
    <ul class="messages">
        {% for message in messages %}
            <div {% if message.tags == 'success' %} class="alert alert-success" role="alert"
                {% elif  message.tags == 'error'%} class="alert alert-danger" role="alert"
                {% endif %}>
                "{{ message }}"
            </div>
        {% endfor %}
    </ul>
{% endif %}

<div class="container-fluid" style="padding-bottom: 80px;">
    <div class="row">
        <div id="lcol">
            {%  block left_sidebar %}
            {% endblock %}
        </div>
        <div class="content">
            {% block content %}
            {% endblock content %}
        </div>
        <div id="rcol">
            {%  block right_sidebar %}
            {% endblock %}
        </div>
    </div>

</div>

{% block footer %}
    {% include 'footer.html' %}
{% endblock footer %}

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="{% static "js/jquery.min.js" %}"></script>
<script>window.jQuery || document.write('<script src="{% static "js/jquery.min.js" %}"><\/script>')</script>
<script src="{% static "js/bootstrap.min.js" %}"></script>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="{% static "js/ie10-viewport-bug-workaround.js" %}"></script>
</body>
</html>

templates/footer.html
<footer class="panel-footer" style="box-sizing: border-box; position: fixed; left: 0; bottom: 0; width: 100%">
    <P style="text-align: center">2016 &copy; Semiol LTD </P>
</footer>

templates/header.html
{% load static %}
<nav class="navbar navbar-default navbar-fixed-top navbar-left navbar-collapse">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            {#            <a class="navbar-left"><img src="{% static "images/SOM.png" %}" height="40"></a>#}
            <span><img src="{% static "images/SOM.png" %}"></span>
            <a class="navbar-brand navbar-right" href="{% url 'index' %}">SemiStorage</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false">Компоненты <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Пасивные компоненты</a></li>
                        <li><a href={% url 'components:components_list' %}>Все компоненты</a></li>
                        <li><a href="#">Электротехнические изделия</a></li>
                        <li role="separator" class="divider"></li>
                        {#                <li class="dropdown-header">Действия</li>#}
                        <li><a href="#">Приход</a></li>
                        <li><a href="#">Расход</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href={% url "components:new_component" %}>Создать компонент</a></li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false">Платы <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Заготовки</a></li>
                        <li><a href="#">Наличие</a></li>
                        <li><a href="#">В производстве</a></li>
                        <li role="separator" class="divider"></li>
                        {#                <li class="dropdown-header">Действия</li>#}
                        <li><a href="#">Приход</a></li>
                        <li><a href="#">Расход</a></li>
                        <li><a href="#">Запуск в производство</a></li>

                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false">Устройства<span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">В производстве</a></li>
                        <li><a href="#">Склад</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#">Запуск в производство</a></li>
                    </ul>
                </li>
                <li><a href="{% url 'suppliers-list' %}">Поставщики</a></li>
                <li><a href="{% url 'search' %}">Поиск</a>
{#                    <form class="navbar-form navbar-right">#}
{#                        <input type="text" class="form-control" placeholder="Поиск...">#}
{#                    </form>#}
                </li>
                {% if request.user.is_authenticated %}
                    <li><a href="{% url 'logout' %}">Logout</a></li>
                {% else %}
                    <li><a href="{% url 'login' %}">Login</a></li>
                {% endif %}
            </ul>

        </div><!--/.nav-collapse -->
    </div>
</nav>

templates/paginate.html
<div style="text-align: center">
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}"><button type="button" class="btn btn-sm btn-primary" >PREV</button></a>
        {% endif %}

        {% for page in paginator.page_range %}
            {% if  paginator.num_pages < 8 %}
                {% if page == page_obj.number %}
                    <span class="label label-default" style="font-size: 20px">{{ page }}</span>
                {% else %}
                    <a href="?page={{ page }}"><button type="button" class="btn btn-sm btn-primary" >{{ page }}</button></a>
                {% endif %}

            {% else %}
                {% if page_obj.number > 5 and  page < page_obj.previous_page_number %}
                    {% if page < 3 %}
                        <a href="?page={{ page }}"><button type="button" class="btn btn-sm btn-primary" >{{ page }}</button></a>
                    {% endif %}
                {% elif page_obj.number > 5 and page == page_obj.previous_page_number  %}
                    <span><button type="button" class="btn btn-sm btn-primary" >...</button></span>
                    <a href="?page={{ page }}"><button type="button" class="btn btn-sm btn-primary" >{{ page }}</button></a>
                {% elif page_obj.number > 1 and page <= page_obj.previous_page_number%}
                    <a href="?page={{ page }}"><button type="button" class="btn btn-sm btn-primary" >{{ page }}</button></a>
                {% endif %}

                {% if page == page_obj.number %}
                    <span class="label label-default" style="font-size: 20px">{{ page }}</span>
                {% endif %}

                {% if forloop.revcounter <= 3 and page == page_obj.next_page_number%}
                    <a href="?page={{ page }}"><button type="button" class="btn btn-sm btn-primary" >{{ page }}</button></a>
                {% elif  forloop.revcounter > 3 and page == page_obj.next_page_number%}
                    <a href="?page={{ page }}"><button type="button" class="btn btn-sm btn-primary" >{{ page }}</button></a>
                    <span><button type="button" class="btn btn-sm btn-primary" >...</button></span>
                {% elif forloop.revcounter <= 2 and forloop.counter > page_obj.number%}
                    <a href="?page={{ page }}"><button type="button" class="btn btn-sm btn-primary" >{{ page }}</button></a>
                {% endif %}
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}"><button type="button" class="btn btn-sm btn-primary" >NEXT</button></a>
        {% endif %}
</div>